apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-dind
  labels:
    app: dind
spec:
  containers:
    - name: dind
      image: docker:dind
      command:
      - cat
      tty: true
      volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  restartPolicy: Always
