apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-{{ .Release.Name }}-{{ .Release.Namespace }}-dind
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /TEST
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
