apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dind
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 2049
      targetPort: 2049
